/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula8ex1_paint.view;


/**
 *
 * @author andre
 */
public class MainPaintView extends javax.swing.JFrame {

    /**
     * Creates new form MainPaintView
     */
    public MainPaintView() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNovoCarro = new javax.swing.JButton();
        jButtonNovoCaminhao = new javax.swing.JButton();
        telaJPanel1 = new aula8ex1_paint.view.TelaJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNovoCarro.setText("Novo Carro");
        jButtonNovoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCarroActionPerformed(evt);
            }
        });

        jButtonNovoCaminhao.setText("Novo Caminhao");
        jButtonNovoCaminhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCaminhaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaJPanel1Layout = new javax.swing.GroupLayout(telaJPanel1);
        telaJPanel1.setLayout(telaJPanel1Layout);
        telaJPanel1Layout.setHorizontalGroup(
            telaJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        telaJPanel1Layout.setVerticalGroup(
            telaJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovoCaminhao)
                    .addComponent(jButtonNovoCarro))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(telaJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovoCarro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovoCaminhao)
                .addGap(34, 34, 34)
                .addComponent(telaJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCarroActionPerformed
        // Só para testar, faremos o codigo aqui mesmo
        telaJPanel1.addNovoCarro();  
        telaJPanel1.repaint();
    }//GEN-LAST:event_jButtonNovoCarroActionPerformed

    private void jButtonNovoCaminhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCaminhaoActionPerformed
        // faremos o codigo aqui
        telaJPanel1.addNovoCaminhao();
        telaJPanel1.repaint();
    }//GEN-LAST:event_jButtonNovoCaminhaoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNovoCaminhao;
    private javax.swing.JButton jButtonNovoCarro;
    private aula8ex1_paint.view.TelaJPanel telaJPanel1;
    // End of variables declaration//GEN-END:variables
}
