/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula10ex1_carros_threadcrud;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author professor
 */
public class PistaCorridaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PistaCorridaJPanel
     */
    private ArrayList<Veiculo> pistaCorrida = null;
    private boolean corridaIniciada = false;
    public PistaCorridaJPanel() {
        initComponents();
    }

    public void setPistaCorrida(ArrayList<Veiculo> pistaCorrida) {
        this.pistaCorrida = pistaCorrida;
    }

    public void setCorridaIniciada(boolean corridaIniciada) {
        this.corridaIniciada = corridaIniciada;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        if(pistaCorrida !=null){
            Iterator<Veiculo> it = pistaCorrida.iterator();
            while(it.hasNext()){
                Veiculo v = (Veiculo) it.next();
                int[] rect1 = v.getRect1();
                int[] rect2 = v.getRect2();
                int[] circ1 = v.getCirc1();
                int[] circ2 = v.getCirc2();
                g.drawRect(rect1[0],rect1[1],rect1[2],rect1[3]);
                g.drawRect(rect2[0],rect2[1],rect2[2],rect2[3]);
                g.drawOval(circ1[0],circ1[1],circ1[2],circ1[3]);
                g.drawOval(circ2[0],circ2[1],circ2[2],circ2[3]);
            }
        }               
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
