/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula8ex1doencajdbc;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author andre
 */
public class DoencaViewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DoencaViewJFrame
     */
    private DefaultListModel<Doenca> defaultListModel;
    public DoencaViewJFrame() {
        
        defaultListModel = new DefaultListModel<Doenca>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeDoencajTextField1 = new javax.swing.JTextField();
        nrPacientesjTextField2 = new javax.swing.JTextField();
        inserirjButton1 = new javax.swing.JButton();
        carregarjButton2 = new javax.swing.JButton();
        limparjButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doencasjList1 = new javax.swing.JList<Doenca>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Doença");

        jLabel2.setText("Nr. Pacientes");

        nomeDoencajTextField1.setText("Sarampo");

        nrPacientesjTextField2.setText("100");

        inserirjButton1.setText("Inserir");

        carregarjButton2.setText("Carregar");

        limparjButton3.setText("Limpar");

        doencasjList1.setModel(defaultListModel);
        jScrollPane1.setViewportView(doencasjList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparjButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nrPacientesjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(nomeDoencajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inserirjButton1)
                            .addComponent(carregarjButton2))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeDoencajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserirjButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nrPacientesjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carregarjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(limparjButton3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Doenca obterDoencaDigitada(){
        String nome = nomeDoencajTextField1.getText();
        int    nrpacientes = Integer.parseInt(nrPacientesjTextField2.getText());
        Doenca d = new Doenca(nome, nrpacientes);       
        return d;
    }
    public void inserirNaLista(Doenca d){
        defaultListModel.addElement(d);
    }
    public void limparLista(){
        defaultListModel.clear();        
    }
    
    public void adicionarInserirListener(ActionListener al){
        inserirjButton1.addActionListener(al);        
    }
    public void adicionarLimparListener(ActionListener al){
        limparjButton3.addActionListener(al);
    }
    public void adicionarCarregarListener(ActionListener al){
        carregarjButton2.addActionListener(al);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carregarjButton2;
    private javax.swing.JList<Doenca> doencasjList1;
    private javax.swing.JButton inserirjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparjButton3;
    private javax.swing.JTextField nomeDoencajTextField1;
    private javax.swing.JTextField nrPacientesjTextField2;
    // End of variables declaration//GEN-END:variables
}
