/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula7excarros;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author andre
 */
public class PistaVeiculosJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PistaVeiculosJPanel
     */
    private ArrayList<Veiculo>  listaPista;

    public ArrayList<Veiculo> getListaPista() {
        return listaPista;
    }

    public void setListaPista(ArrayList<Veiculo> listaPista) {
        this.listaPista = listaPista;
    }
    public PistaVeiculosJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        if(listaPista!=null){
          Iterator<Veiculo> it = listaPista.iterator();
           while(it.hasNext()){
               Veiculo v = it.next();
               int c = v.getComprimento();
               int l = v.getLargura();
               g.drawString(v.getNomeVeiculo(), v.getPosX(), 
                                                v.getPosY());
               g.drawRect(v.getPosX(),v.getPosY(),l, c);
           }   
        }
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
