/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula7ex1jdbc_exames;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author andre
 */
public class ExamesJFrame extends javax.swing.JFrame {

    private DefaultListModel<Exame> listaModel;
    public ExamesJFrame() {
        listaModel = new DefaultListModel<Exame>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeExamejTextField1 = new javax.swing.JTextField();
        precoExamejTextField2 = new javax.swing.JTextField();
        insereListajButton1 = new javax.swing.JButton();
        insereBancojButton2 = new javax.swing.JButton();
        limpaListajButton3 = new javax.swing.JButton();
        carregaBancojButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaExamesjList1 = new javax.swing.JList<Exame>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Exame:");

        jLabel2.setText("Preço R$ ");

        nomeExamejTextField1.setText("Sangue");

        precoExamejTextField2.setText("100");

        insereListajButton1.setText("Insserir Lista");

        insereBancojButton2.setText("Inserir Banco");

        limpaListajButton3.setText("Limpa Lista");

        carregaBancojButton4.setText("Carrega Banco");

        listaExamesjList1.setModel(listaModel);
        jScrollPane1.setViewportView(listaExamesjList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(carregaBancojButton4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(nomeExamejTextField1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(precoExamejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(insereListajButton1)
                        .addComponent(limpaListajButton3))
                    .addComponent(insereBancojButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomeExamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(precoExamejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insereListajButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpaListajButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insereBancojButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carregaBancojButton4))
                    .addComponent(jScrollPane1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Exame obterExame(){
        String nome = nomeExamejTextField1.getText();
        double preco = Double.parseDouble(precoExamejTextField2.getText());
        Exame ex = new Exame(nome, preco);
        return ex;
    }   
    public void insereLista(Exame ex){
        listaModel.addElement(ex);        
    }
    public void limparLista(){
        listaModel.clear();
    }
    public void addInserirListaListener(ActionListener al){
        insereListajButton1.addActionListener(al);
    }
    public void addInserirBancoListener(ActionListener al){
        insereBancojButton2.addActionListener(al);
    }
    public void addLimpaListaListener(ActionListener al){
        limpaListajButton3.addActionListener(al);
    }
    public void addCarregaListaListener(ActionListener al){
        carregaBancojButton4.addActionListener(al);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carregaBancojButton4;
    private javax.swing.JButton insereBancojButton2;
    private javax.swing.JButton insereListajButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpaListajButton3;
    private javax.swing.JList<Exame> listaExamesjList1;
    private javax.swing.JTextField nomeExamejTextField1;
    private javax.swing.JTextField precoExamejTextField2;
    // End of variables declaration//GEN-END:variables
}
