/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula11ex1_carrinhos;

import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author andre
 */
public class CarrinhosViewJFrame extends javax.swing.JFrame {
    private ArrayList<Veiculo> listaVeiculos;
    private boolean iniciar = false;
    /**
     * Creates new form CarrinhosViewJFrame
     */
    public CarrinhosViewJFrame() {
        listaVeiculos = new ArrayList<Veiculo>();
        initComponents();
        pistaCorridaJPanel1.setListaVeiculos(listaVeiculos);
        pistaCorridaJPanel1.setIniciar(iniciar);
    }

    public Veiculo obterVeiculoDigitado(){
        String jogador = jogadorjTextField1.getText();
        String objeto  = objetojTextField2.getText();
        int xi = 50, yi = 10* listaVeiculos.size();
        
        if(objeto.equalsIgnoreCase("Carro")){
            return new Carrinho(jogador, xi, yi);
        }
        if(objeto.equalsIgnoreCase("Moto")){
            return new Moto(jogador, xi, yi);
        }      
        
        if(objeto.equalsIgnoreCase("Aviao")){
            return new Aviao(jogador, xi, yi);
        }
        return new VeicGeral(jogador, xi, yi);

    }
    public void insereVeiculo(Veiculo v){
        listaVeiculos.add(v);
        pistaCorridaJPanel1.repaint();
    }
    public ArrayList<Veiculo> obterListaVeiculos(){
        return listaVeiculos;
    }
    
    public void addInsereListener(ActionListener al){
        inserejButton1.addActionListener(al);
    }
    public void addDispararListener(ActionListener al){
        disparajButton2.addActionListener(al);
    }
    public void addPararListener(ActionListener al){
        pararjButton3.addActionListener(al);
    }

    public boolean isIniciar() {
        return iniciar;
    }

    public void setIniciar(boolean iniciar) {
        this.iniciar = iniciar;
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jogadorjTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        objetojTextField2 = new javax.swing.JTextField();
        inserejButton1 = new javax.swing.JButton();
        disparajButton2 = new javax.swing.JButton();
        pararjButton3 = new javax.swing.JButton();
        pistaCorridaJPanel1 = new aula11ex1_carrinhos.PistaCorridaJPanel();

        jLabel1.setText("Jogador");

        jogadorjTextField1.setText("XMaximus");

        jLabel2.setText("Objeto");

        objetojTextField2.setText("Carro");

        inserejButton1.setText("INSERE");

        disparajButton2.setText("DISPARA");

        pararjButton3.setText("PARAR");

        javax.swing.GroupLayout pistaCorridaJPanel1Layout = new javax.swing.GroupLayout(pistaCorridaJPanel1);
        pistaCorridaJPanel1.setLayout(pistaCorridaJPanel1Layout);
        pistaCorridaJPanel1Layout.setHorizontalGroup(
            pistaCorridaJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        pistaCorridaJPanel1Layout.setVerticalGroup(
            pistaCorridaJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jogadorjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(objetojTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inserejButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(disparajButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pararjButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pistaCorridaJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jogadorjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(objetojTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserejButton1)
                    .addComponent(disparajButton2)
                    .addComponent(pararjButton3))
                .addGap(18, 18, 18)
                .addComponent(pistaCorridaJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton disparajButton2;
    private javax.swing.JButton inserejButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jogadorjTextField1;
    private javax.swing.JTextField objetojTextField2;
    private javax.swing.JButton pararjButton3;
    private aula11ex1_carrinhos.PistaCorridaJPanel pistaCorridaJPanel1;
    // End of variables declaration//GEN-END:variables
}
