/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula6ex1curso;

import java.awt.event.ActionListener;

/**
 *
 * @author andre
 */
public class CursosNewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CursosNewJFrame
     */
    public CursosNewJFrame() {
        initComponents();
    }
    
    
    public Curso obtemCurso(){
        String nome = cursojTextField1.getText();
        double preco = Double.parseDouble(precojTextField2.getText());
        Curso c = new Curso(nome, preco);
        return c;
    }
    public void mostrarTotal(double total){
        totaljTextField3.setText("R$ "+total);
    }
    
    public void addInserirListener(ActionListener al){
        inserirjButton1.addActionListener(al);        
    }
    public void addTotalizarListener(ActionListener al){
        totalizarjButton2.addActionListener(al);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cursojTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        precojTextField2 = new javax.swing.JTextField();
        inserirjButton1 = new javax.swing.JButton();
        totalizarjButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totaljTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cursos");

        jLabel2.setText("Preço R$");

        inserirjButton1.setText("Inserir");

        totalizarjButton2.setText("totalizar");

        jLabel3.setText("Total");

        totaljTextField3.setText("               ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inserirjButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(totaljTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cursojTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(precojTextField2)))
                    .addComponent(totalizarjButton2))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cursojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(precojTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(inserirjButton1)
                .addGap(18, 18, 18)
                .addComponent(totalizarjButton2)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totaljTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
   
    

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cursojTextField1;
    private javax.swing.JButton inserirjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField precojTextField2;
    private javax.swing.JButton totalizarjButton2;
    private javax.swing.JTextField totaljTextField3;
    // End of variables declaration//GEN-END:variables
}
